# Generated by Django 4.2.3 on 2023-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessrecord',
            name='department',
            field=models.CharField(default='ECE', max_length=100),
        ),
        migrations.AddField(
            model_name='acessrecord',
            name='employe',
            field=models.CharField(default='RAJ', max_length=100),
        ),
    ]
